trigger:
 paths:
   include:
     - src/*

stages:
  - stage: build
    displayName: 'gradle build'
    jobs:
      - job: build
        pool:
         name: 'bit2'
         demands:
          - agent.name -equals react-frontend
        displayName: 'gradle build'
        steps:
          - script: |
              ls
              gradle npmBuild
            displayName: 'gradle build'
            
  - stage: publish
    displayName: 'Publish Artifact'
    jobs:
      - job: publish
        pool:
         name: 'bit2'
         demands:
          - agent.name -equals react-frontend
        displayName: 'Publish Artifact'
        steps:
        - checkout: none
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'build'
            publishLocation: 'Container'
            StoreAsTar: true

