trigger:
 paths:
   include:
     - src/*

stages:
  - stage: build
    displayName: 'gradle build'
    jobs:
      - job: build
        pool:
         name: 'bit2'
         demands:
          - agent.name -equals react-frontend
        displayName: 'gradle build'
        steps:
          - script: |
              ls
              gradle npmBuild
            displayName: 'gradle build'
            
  - stage: publish
    displayName: 'Publish Artifact'
    jobs:
      - job: publish
        pool:
         name: 'bit2'
         demands:
          - agent.name -equals react-frontend
        displayName: 'Publish Artifact'
        steps:
        - checkout: none
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build-directory)'
            ArtifactName: 'build'
            publishLocation: 'Container'
            StoreAsTar: true
 
  - stage: CopyArtifact
    displayName: 'Copy Artifact'
    jobs:
      - job: copy
        pool:
         name: 'bit2'
         demands:
          - agent.name -equals react-frontend
        displayName: 'Copy Artifact'
        steps:
        - checkout: none
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'build'
            downloadPath: '$(Pipeline.Workspace)/artifact'
        - script: |
            cp -r $(Pipeline.Workspace)/artifact/* /home/yogendra/publish
            cd /home/yogendra/publish/build
            tar -xvf *.tar
            rm -rf *.tar
          displayName: 'Copy artifact to destination folder'
  
