trigger:
 paths:
   include:
     - src/*

pool:
  name: 'bit2'

stages:
  - stage: build
    displayName: 'gradle build'
    jobs:
      - job: build
        displayName: 'gradle build'
        steps:
          - script: |
              sudo gradle build
            displayName: 'gradle build'
